version: '2'

services:
  _base:
    image: openjdk:8-jdk-alpine
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle/caches
    working_dir: /app

  api:
    extends:
      service: _base
    command: ["./gradlew", "bootRun"]
    ports:
      - "8080:8080"

volumes:
  gradle-cache:
